# fly.toml file generated for marvelheroes on 2022-10-17T18:20:42-04:00

app = "marvelheroes"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  SECRET = "iDontlikeanyflavouroficeCreamThatisnotChocolatebnChocolateisSuperior!!!"
  DEPLOYED_URL = "mongodb+srv://angie:angelica10@marvelish.ahllsgt.mongodb.net/marvelheroes?retryWrites=true&w=majority"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
